### ISSUE TITLE
Error for STDOUT

### ISSUE THREAD

**Issue by mcki0127** [kalyabin/geonames-importer#1]
I'm getting the following error for the cities.php file: 
`Use of undefined constant STDOUT - assumed 'STDOUT'`
Am I doing something wrong?

**Comment by kalyabin** [comment]
What version of php do you use? did you attempt to run this code at console?

**Comment by mcki0127** [comment]
Php version:  5.5.9-1ubuntu4.19
I tried in the console and it works...sort of.  The console prints out an array for each line as it is downloaded, and then ends with this:

```
Consume city:
Array
(
    [geonameid] => 1106542
    [name] => Chitungwiza
    [asciiname] => Chitungwiza
    [alternatenames] => Chitungviza,Chitungwiza,Citungviza,Gorad Chytungviza,chytwngwyza,Čitungviza,Горад Чытунгвіза,Читунгвиза,Читунгвіза,چیتونگویزا
    [latitude] => -18.01274
    [longitude] => 31.07555
    [feature class] => P
    [feature code] => PPL
    [country code] => ZW
    [cc2] =>
    [admin1 code] => 10
    [admin2 code] =>
    [admin3 code] =>
    [admin4 code] =>
    [population] => 340360
    [elevation] =>
    [dem] => 1435
    [timezone] => Africa/Harare
    [modification date] => 2012-01-20
)

End parse file /tmp//42bd68d2823aee6a2ea6bf29ca5fb38e/cities15000.txt...
Remove temporary file: done
```

The file cities15000.txt or cities15000.zip is nowhere to be found.  Unless of course it's written to a different filename?

**Comment by kalyabin** [comment]
If you want to use it in the frontend, please type such this before downloading:

``` php
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));
```

`The file cities15000.txt or cities15000.zip is nowhere to be found. Unless of course it's written to a different filename?`

Geonames importer works as a connector to CSV files and never saves this files on a disk. You can use it like this:

``` php
// connect to database
$dbh = new PDO('mysql:host=localhost;dbname=geobase', 'user', 'password');
// creates consumer for your cities base
$importer = new \kalyabin\geonames\importer\City('/tmp/', 'cities5000.zip', function($city) use ($dbh) {
    // save city to MySQL database, for example:
   $stmt = $dbh->preapre('INSERT INTO city SET geonameid = :geonameid, country_code = :countryCode, name = :name');
   $stmt->bindParam(':geonameid', $city['geonameid']);
   $stmt->bindParam(':countryCode', $city['country code']);
   $stmt->bindParam(':name', $city['name']);
   $stmt->execute();
});
// run importer
$importer->process();
```

It helps you to download and to parse files, and to use it for regular sync with geonames.org, but you must to write a consumer to save geonames data for your specific case.

**Comment by mcki0127** [comment]
Got it.  Thanks much for your help!  It's a great extension.
